# Use an official Python 2.7 slim image as a base
FROM python:2.7-slim

# Create a directory for the topology2.py
WORKDIR /app

# Copy topology2.py into the container
COPY topology2.py ./

# Command to run topology2.py
CMD ["python", "topology2.py"]

