# Use an official Python 2.7 slim image as a base
FROM python:2.7-slim

# Create a directory for the topology1.py
WORKDIR /app

# Copy topology1.py into the container
COPY topology1.py ./

# Command to run topology1.py
CMD ["python", "topology1.py"]

